site_name: CodeMate
site_description: Python syntax generator based on Object-Oriented Programing, type hints, and simplicity.
#site_url: ... todo
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: amber
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: amber
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  icon:
    repo: fontawesome/brands/github-alt
#  logo: .svg todo
#  favicon: .png todo
  language: en
repo_name: Cyberproof/codemate
repo_url: https://github.com/Cyberproof/codemate
edit_uri: ""
#google_analytics: ""todo
plugins:
- search
- markdownextradata:
    data: data
nav:
- CodeMate: index.md
#- Usage:
#    - todo
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: false
#- markdown_include.include:
#    base_path: docs todo
- admonition
- pymdownx.highlight
- pymdownx.extra
- codehilite
- extra
